env:
  browser: true
  es2021: true
extends:
  - 'plugin:vue/essential'
  - standard
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - vue
rules:
  semi: ["warn"]
  quotes: ["off", "double", {"avoidEscape": true}]
  space-before-function-paren: ["off"]
  space-before-blocks: ["off"]
  camelcase: ["off"]
  eqeqeq: ["warn", "smart"]
  no-cond-assign: ["warn"]
  no-var: ["off"]
  no-multi-spaces: ["off"]
  arrow-spacing: ["warn"]
  no-trailing-space: ["off"]
  no-trailing-spaces: ["off"]
  space-infix-ops: ["warn"]
  block-spacing: ["off"]
  object-curly-spacing: ["off"]